### ISSUE TITLE
Errors in included file are not reported correctly.

### ISSUE THREAD

**Issue by plietar** [microsoft/verona#11]
```pony
// foo.verona
use "bar.verona"
```

```pony
// bar.verona
class A {
  m(x: T) { } // Use a non-existent type T
}
```

Compiling `foo.verona` will cause an error, as expected, but the location is incorrect:
```
$ ./dist/veronac foo.bar
foo.verona:0:6: error: Cannot find value for symbol 'T'
// foo.verona
     ^
1 error generated
```

The error should be at `bar.verona:3:8`, but `foo.verona:0:6` is reported instead.

**Comment by 0paIescent** [comment]
I know this has already been assigned to @davidchisnall, but I wanted to take a crack at it myself out of curiosity.

Doing a quick and dirty dump of the entities in `bar.verona` immediately after parsing, it's obvious that the source_ranges are getting mixed in with garbage data. And those locations are the same between every compilation too, so that limits what it could be.

```
printing all entities in .//bar.verona
---------------------------------------------
A.source_range(2147483648, 2147483649)
```

I'll take a deeper look at the parsing logic and see if I can find something.

**Comment by 0paIescent** [comment]
I was mistaken in my previous comment concerning garbage data.

It looks like Verona only has support for one file right now as said here in `source_manager.h:631`:
```
    /**
     * Number of bits used to store the file index in the compressed encoding.
     *
     * We currently support only one file, so have space for two (0 and 1) in
     * this encoding.
     */
    static const unsigned small_file_bits = 1;
```

Now, changing this to a larger number will of course increase the number of allowed files exponentially since it bit shifts to determine `min_large_file`, and a lot of other values in SourceManager depend on `small_file_bits` and I'm not knowledgeable enough to know exactly what kind of impact that would have. Increasing `small_file_bits` does fix this issue, however only up to a point. Setting `small_file_bits = 2` only defers the error to when you compile three files at once instead of just two.

I haven't fixed it, but hopefully I've managed to help get others there a bit quicker.

**Comment by plietar** [comment]
Thanks for having a look.
From what I understand of the SourceManager, it has a small and large encoding of source locations. The latter is used when the source location doesn’t fit in the bits, and the expanded value is stored in a vector and the large encoding represents the index.

So even if small_file_bits is 1, the compiler should fall back to this large encoding and work properly, albeit with a tiny overhead.

Btw the compiler always includes `stdlib/builtin`, which explains why it starts breaking down when we add an extra file. That is the third file, so it stops fitting in the 1 bit.

I also think the “We currently support only one file” comment was written a while ago, before we had an stdlib or a use statement.

**Comment by 0paIescent** [comment]
Thanks for the explanation, C++ isn't my strong suit so that helped me
understand it more. Also, I had completely forgotten that `stdlib/builtin`
was considered a "file" here so that makes sense.

I'll take more of a look at it then, now that I know more of how it works,
and that it _should_ be using the fallback.

**Comment by 0paIescent** [comment]
The discriminator offset is the high bit, so `1 << discriminator_offset` should be the first location in which we start storing in the expanded form right?

**Comment by 0paIescent** [comment]
The way I've interpreted it is that any number over the starting `next_source_location` is deemed an expanded source, therefore anything with the 32nd bit set would be expanded. However, if I'm understanding this wrong then everything following this is wrong as well. Bit operations aren't my strong suit.

Here's my proposal for a fix.
\
Changing this:
```c++
return extract_bits<SourceLocation, discriminator_offset, 1>(l) == 0;
```
to this:
```c++
return ((l >> discriminator_offset) & static_cast<SourceLocation>(1)) == 0;
```
\
The `next_source_location` starts out as `2147483648`, and the `discriminator_offset` is `31`, which if put through `extract_bits<SourceLocation, discriminator_offset, 1>(next_source_location)` comes out as 0.
\
The change is essentially a reimplementation of `extract_bits` so that it actually pulls out the 32nd bit, as of right know it grabs the 31st bit since it subtracts the width from high bit before shifting the supplied bitfield.
\
Every test that passed on master passed on my branch.

**Comment by mjp41** [comment]
@0paIescent please submit a PR, and @davidchisnall will review.  There are a lot of tricky corner cases in these kind of representations ;-)

From your description, it sounds like `extract_bits` is incorrect?  Or doesn't cover the `is_small_source_location`  use case?  Or is `is_small_source_location`  not calling `extract_bits` with the correct arguments? Would something like
```
extract_bits<SourceLocation, discriminator_offset - 1, 1>(l) == 0;
```
work?
