### ISSUE TITLE
Syntax highlighting

### ISSUE THREAD

**Issue by KodrAus** [microsoft/verona#145]
**UPDATE:** Search the VS Code marketplace for _Verona_!

-----

Hey! 👋 

I'm not sure if you all have something already you use to syntax highlight your Verona (maybe just using C# or C++?) but I wanted to try my hand at writing something specific to the language, so have [put together a rough-and-ready VS Code plugin](https://github.com/KodrAus/vscode-verona). It does a reasonable job of highlighting, ~~but currently _only_ highlights within classes, so standalone expressions aren't handled yet.~~

I'd like to spend a little more time on tightening things up and filling in gaps before publishing something to the marketplace, but thought I'd drop a line here first in case you already had thoughts or plans for this, or if anybody else wanting to dig into the language is looking for syntax highlighting.

**Comment by davidchisnall** [comment]
Thanks, that's really nice!

We are planning to support the language server protocol in the compiler, so that we can get syntax highlighting, autocompletion, error reporting, and so on in an IDE, but that's still quiet a way away.  Your plugin is a great interim (and is likely to continue to be a lot faster - as I recall, VS Code can use in-process JSON grammars for quick highlighting as you type and replace the colours with a slower LSP implementation when it returns, so it's likely to be useful for a long time).

**Comment by rengolin** [comment]
Another cool thing would be to add it to [Pygments](https://github.com/pygments/pygments). I think it's still the way GitHub does highlight in file view and code review.

**Comment by davidchisnall** [comment]
I would love to see this in Pygments.  I have added some Markdown things that use ```verona escapes, but currently GitHub just renders them withotu syntax highlighting.

**Comment by mjp41** [comment]
Just tried this, it is awesome.  Thanks for doing it.

**Comment by rengolin** [comment]
Used this today (I know, a year later), it's really nice!

I'll close this ticket as you have "delivered" and the syntax is "in production". When I opened a `.verona` file in Code it automatically suggested me to use it and with one click it was installed. It doesn't get better than that! :)

If we need to change something on the syntax as it changes, we can open a new ticket for that.

Thanks again for doing it!
