### ISSUE TITLE
Use C++ casts instead of C-style casts in the runtime

### ISSUE THREAD

**Issue by Theodus** [microsoft/verona#217]

**Comment by davidchisnall** [comment]
There's a clang-tidy thing that will apply fixits to most of these automatically.  

It would be good eventually to add some clang-tidy checks to CI.  I did run all of the runtime through clang-tidy and clean things up a while ago, but never got around to doing the CI thing.

**Comment by rengolin** [comment]
Before we add to CI, it would be good to have an automated way to do in our development environments (vim, vscode, etc), so that we don't get reminders only after submitting the PR.

**Comment by davidchisnall** [comment]
Yup, I'd want a clang-format build target and then a check in CI that running it didn't add any diffs, as we do with clang-format.

**Comment by rengolin** [comment]
We have a clang format target but it doesn't work for me because it specifically searches for `clang-format-9` which I don't have.

Matt said the problem is incompatibility between 8 and 9 (10 seems to be the same as 9), but that's very sub-optimal.

If clang-tidy has the same instability issues, we will get into the same kind of trouble.

**Comment by plietar** [comment]
> We have a clang format target but it doesn't work for me because it specifically searches for clang-format-9 which I don't have.
You can `-DCLANG_FORMAT=...` I think, but obviously incompatibilities is still a problem.

**Comment by rengolin** [comment]
I'm a Linux user, so obviously I created a symlink. And that will haunt me if I install the actual `clang-format-9`, but hey, that's in the future. :)
