### ISSUE TITLE
Questions about clang_interface.cc

### ISSUE THREAD

**Issue by rengolin** [microsoft/verona#304]
A few questions about the `clang_interface.cc` example in `experiments`.

Q. There are two intents here: read a header file and parse all external declarations and parse a source file and emit LLVM IR. Right?

Q. Finding the headers is a complex environment problem that Clang's driver has a lot of boilerplate to implement. Are we supposed to replicate all that? Is it even possible to reuse it? IIRC, it's mostly hard-coded stuff...

Q. Once we have the file, you find the includes and enable incremental pre-processing. Will that run lazily once we try to match things? Or will that pre-process the while file once we try the first time?

Q. There are a lot of hard-coded stuff, from paths, strings to sequence of calls in "the right order". We'll have to factor all that out into an API to be used by Verona. Have you thought about that already and do you see a reasonably simple path? Or is it going to be gruesome like most API refactorings?

Q. I like your type matchers very much. Do you plan to implement similar matchers for function declarations, too? Do you see a way to stop other matchers if one of them has found something? Otherwise, the more we have, more of them will be scanning the whole graph for nothing.

Q. The overall `CXXInterface` looks fine to me, though I haven't touched the Clang AST code in many years now. I'm imagining this would be the entry point into Verona, right?

```
CXXInterface usercode("some file/header");
auto func = usercode.getFunction("name", args, etc);
auto engine = WASMGen() | MMUGen() | CHERIGen();
auto code = engine.generate(func);
auto future = code.run();
```

Q. The heavy use of the (unstable) C++ API from Clang will create a strong dependency with the project, like the one we already have with MLIR and will soon have with LLVM. I see no way around that, but that will make update LLVM sources more and more painful. We'll probably soon need patches applied on top of the LLVM rebase, like many derived projects do (including Pony).

**Comment by davidchisnall** [comment]
First, a high-level disclaimer: This started as an experiment to see whether clang exposed interfaces that did everything that we needed and is both incomplete and does not always implement things in a sensible way.  I was hoping to have more time to work on it, but committed it as an experiment so at least it didn't get lost, because I kept being preempted by other urgent things.  


>Q. There are two intents here: read a header file and parse all external declarations and parse a source file and emit LLVM IR. Right?

Yes, the goal is to be able to write things vaguely like this in Verona:

```verona
[[interface="somelib.h", implementation="somelib.so, language="c++"]]
class LLVM;

...

// Create a new instance of the LLVM library using process isolation for sandboxing
var llvm = new LLVM() # ProcessSandbox
// Create a new llvm::Module in the sandboxed region, this will involve a cross-domain call
var m = new LLVM.llvm.Module in llvm;
```

And then call other methods on `m`.  We need two things for this to work:

 - To be able to find all of the symbol names and their types exposed by the C/C++/whatever module.
 - To be able to synthesize and template instantiations that might not be present in the .so and wrappers that make it easy for the Verona cross-domain call interface to handle them.

> Q. Finding the headers is a complex environment problem that Clang's driver has a lot of boilerplate to implement. Are we supposed to replicate all that? Is it even possible to reuse it? IIRC, it's mostly hard-coded stuff...

I think most of this is in the ToolChain file.  For now, I was just passing a few `-I` flags.  That's probably fine for MVP, but longer-term we'll need something bigger.

> Q. Once we have the file, you find the includes and enable incremental pre-processing. Will that run lazily once we try to match things? Or will that pre-process the while file once we try the first time?

The thing I was experimenting with (which may not be the right approach) was generating a PCH once (which can take a few seconds for a large set of headers) and then instantiating that once for querying and once for codegen.  I'd expect `veronac` to manage maintaining the PCH transparently.  We can do that by using the -M family of flags to track the dependencies, but for MVP having a flag to delete it explicitly might be fine.

> Q. There are a lot of hard-coded stuff, from paths, strings to sequence of calls in "the right order". We'll have to factor all that out into an API to be used by Verona. Have you thought about that already and do you see a reasonably simple path? Or is it going to be gruesome like most API refactorings?

The ordering of calls is going to be slightly painful, hopefully we can expose this behind an interface that gets most of it right for you.

> Q. I like your type matchers very much. Do you plan to implement similar matchers for function declarations, too? Do you see a way to stop other matchers if one of them has found something? Otherwise, the more we have, more of them will be scanning the whole graph for nothing.

The type matchers are quite slow, so I'm not sure that they're the right approach (though they at least show that the clang AST contains the things we need).  We may want to do a single traversal of the AST ourself and find the right Decl nodes and put them in an index structure.  

> Q. The overall CXXInterface looks fine to me, though I haven't touched the Clang AST code in many years now. I'm imagining this would be the entry point into Verona, right?

Yes, something like this at least.  This was a first cut, so may be wrong...

```c++
CXXInterface usercode("some file/header");
auto func = usercode.getFunction("name", args, etc);
auto engine = WASMGen() | MMUGen() | CHERIGen();
auto code = engine.generate(func);
auto future = code.run();
```

That's sufficient for simple non-templated things (though for C++ `"name"` will need to be a fully qualified name).  We will need to explicitly instantiate templated functions.  The code from [about here](https://github.com/microsoft/verona/blob/4c471d4071f1b802b4bb97e5a8aeaf8e33aa4aa0/experiments/clang_interface/clang_interface.cc#L705) shows how to instantiate a templated type.  This is [then used](https://github.com/microsoft/verona/blob/4c471d4071f1b802b4bb97e5a8aeaf8e33aa4aa0/experiments/clang_interface/clang_interface.cc#L726) to create a wrapper function.  

Given our sandboxing requirements, there are two things that we'll need.  On the unsafe side of the interface, we'll want to create these little wrapper functions that take all of the arguments as pointers (so the calling convention is trivial and understandable) and a run loop that takes an exported function index and an argument tuple (struct).  On the safe side, we'll need to allocate a buffer in the sandbox's memory and do the cross-domain call.

If we have a sequence of calls into the same sandbox, then we want to ideally turn them into a single cross-domain call.  Given the cost of most cross-domain call mechanisms, I expect that users will often expose unsafe libraries as cowns and when over time with a closure that runs a bunch of in-sandbox code and returns a promise.  

> Q. The heavy use of the (unstable) C++ API from Clang will create a strong dependency with the project, like the one we already have with MLIR and will soon have with LLVM. I see no way around that, but that will make update LLVM sources more and more painful. We'll probably soon need patches applied on top of the LLVM rebase, like many derived projects do (including Pony).

I think that everything that we're doing here is generally useful, so once we know what the interfaces should look like it should be possible for us to write a libClangFFI or similar and upstream it.

**Comment by rengolin** [comment]
> First, a high-level disclaimer: This started as an experiment to see whether clang exposed interfaces that did everything that we needed and is both incomplete and does not always implement things in a sensible way. I was hoping to have more time to work on it, but committed it as an experiment so at least it didn't get lost, because I kept being preempted by other urgent things.

No worries, this is exactly what I expected.

> The type matchers are quite slow, so I'm not sure that they're the right approach (though they at least show that the clang AST contains the things we need). We may want to do a single traversal of the AST ourself and find the right Decl nodes and put them in an index structure.

A single traversal would be ideal, yes. We can change the matcher's function to a list of object types or even patterns. The order in which you insert the patterns will determine the match that is most important (or most specific).

> That's sufficient for simple non-templated things (though for C++ `"name"` will need to be a fully qualified name).

Templated stuff would probably need further code-gen (then what's in the SO) if the implementation is in the header only, but I'm assuming we can do that at compile time, given that all Verona types must be known and concrete before codegen. This corroborates the two-stage pass you proposed: first loads all the headers and expose the interfaces, then run type inference/reification to make all templates concrete, then link with the remaining SO object by generating FFI calls and wrappers.

> If we have a sequence of calls into the same sandbox, then we want to ideally turn them into a single cross-domain call. Given the cost of most cross-domain call mechanisms, I expect that users will often expose unsafe libraries as cowns and when over time with a closure that runs a bunch of in-sandbox code and returns a promise.

This will probably require an "optimisation" step in MLIR to bundle those operations into one. The simple thing is if each feeds into the next, forming a chain. But if we have other "safe" Verona code intermixed, it will be hard to separate them.

We could do reordering if possible, assuming that the Verona side won't have side effects (unless specified), but if we're intermixing Verona and external code, chances are that won't work.

> I think that everything that we're doing here is generally useful, so once we know what the interfaces should look like it should be possible for us to write a libClangFFI or similar and upstream it.

I see, with the promise of being as stable as the C API. But unless we find other people willing to co-maintain, we may end up spending a lot of time fixing tests on the Clang side, though, hopefully less than if we do on our side...

A new question:

Q. We will need some type equivalence to resolve templates in C++ from types in Verona. Or we'll have to declare C++ types in Verona as a class. However, capabilities won't be easily (or correctly) translatable. For example, `immutable` is not the same as `const` (in C). What are the implications of this?

I imagine a translation structure such as:
```pony
class C++ {
  type char = ...; // whatever the ABI defines!
  type int = S32 & mut;
  type unsigned_const_long = U64 & imm; // probably wrong
  type float = F32 & mut;
  ...
}
```

Then, a C++ template:
```cpp
class Foo {
  template <class T> func(T& a);
}
```

would be called in Verona as something like:
```pony
[[interface="somelib.h", implementation="somelib.so, language="c++"]]
class Foo;
let foo = new Foo() # ProcessSandbox
let f = 3.14;
let fut = foo.func[C++.float](f);
```
which during reification will codegen the `float` version of `func`.

**Comment by davidchisnall** [comment]
> For example, immutable is not the same as const (in C). What are the implications of this?

I think that's actually simple: All C++ types other than primitives are `mut`, in the region of the sandbox instance, primitives (integers / floats) are `imm` (fields [including globals, whcih n.  I would think of `const` as just another subtype, so that `const X` is a subtype of `X` from the Verona perspective, and possibly expose `const_cast` as a generic C++ function (rather than a built-in) that takes a `const X` and returns an `X`.  @sylvanc, what do you think?

In your example, the `T&` would implicitly be a `mut & T*`, which means that you couldn't use `f` here, you'd need to do something like:

```
let f = new C++.float(3.14) in foo;
let fut = foo.func[C++.float](f);
```

If it were `T` and not `T*` then I think your example would work.

**Comment by rengolin** [comment]
With the current clang code in `src/interop` and the new document proposed in #401, we can close this Q&A.
