### ISSUE TITLE
New MLIR ODS type declaration

### ISSUE THREAD

**Issue by rengolin** [microsoft/verona#331]
MLIR has a new [ODS type definition](https://mlir.llvm.org/docs/OpDefinitions/#type-definitions) that we may be able to use for our interned types. Though, to me, it still looks like moving the C++ boilerplate to the table-gen files (although less of it). 

It does allow use in the table-gen operation definitions, but we're getting mostly unknown types, the type inference is independent of the table-gen code and the complexity of type unions and intersections is too great for a clean ODS usage.

Overall, I'm not convinced it would help us. The current table-gen representation is clean enough as it is.

@plietar

**Comment by plietar** [comment]
I think this will help with reducing the boilerplate involved in the definition of types.

I’m not sure we can use the print and parsing “dispatch” functionality, because our print and parse have an extra “stack” argument, used to handle recursive classes.

Like you’ve mentioned, it won’t help us when it comes to defining type rules for operations.
