### ISSUE TITLE
Typed AST

### ISSUE THREAD

**Issue by plietar** [microsoft/verona#344]
The compiler currently uses an "untyped" AST, which is essentially an S-expression. This makes working on it very painful and code hard to maintain, as there is no central definition of what the shape of the tree needs to be.

We should instead replace it with an explicit and typed AST, akin to [what the original prototype had](https://github.com/microsoft/verona/blob/4d6f471b28f5223aa5468e4918f9ea888ced3315/src/compiler/ast.h).

The plan for now is:
1. Define the typed AST
2. Add a translation pass from the untyped AST to the typed one
3. Change the AST->MLIR lowering to operate on the typed AST.
4. Incrementally shift existing passes from the untyped AST to the typed one. This needs to happen in reverse compared to the execution order.
5. Make the parser produce a typed AST. There are different ways we can achieve this, either by using peglib's semantic actions, or by writing the parser by hand, or we never do this step and keep the untyped->typed conversion "forever" (until the next time we rewrite the compiler).
6. Delete all untyped AST code.

There's a couple of open questions on the design of the AST itself:

- How are variants of expressions, types, class members, ..., represented?
    - Abstract class with concrete subclasses.
        - This is what the prototype's AST used.
        - Should we set up [LLVM-style RTTI](https://llvm.org/docs/HowToSetUpLLVMStyleRTTI.html)?
    - `typedef std::variant<FooExpr, BarExpr, ...> Expr;`
        - This is what the prototype's IR used.
- How are variants traversed, aka [the expression problem](https://en.wikipedia.org/wiki/Expression_problem):
    - Add virtual methods to each variant.
    - Use a visitor pattern
    - std::visit (assuming we chose `std::variant`)
    - LLVM TypeSwitch
    - dynamic_cast
    - Use a [cast + visitor pattern](https://github.com/microsoft/verona/blob/4d6f471b28f5223aa5468e4918f9ea888ced3315/src/compiler/visitor.h). This allows the visitor to be templated over additional arguments and a return type.
- How are source locations represented? Do all nodes carry a location, or only select ones?
- How are symbol tables and symbol references represented?
    - In particular, I think that after a dedicated resolution pass, all symbol references have direct pointers to the defining node. Ulterior passes can directly access that pointer and use it as a simple unique identifier, rather than reimplementing their own lookup tables.
- Are strings in the AST interned?
- Can we reuse any of the original prototype's AST, visitor infrastructure and name resolution pass?

cc @rengolin @sylvanc @mjp41

**Comment by rengolin** [comment]
Hi Paul, thanks for the detailed description, it's an excellent starting point.

You can see how the MLIR generator uses the AST [here](https://github.com/microsoft/verona/blob/master/src/mlir/ast-utils.h). I have extracted all functionality there exactly for this reason, so we can design an easier-to-use AST library (or a fully typed AST).

Answer to some questions:

>     * Should we set up [LLVM-style RTTI](https://llvm.org/docs/HowToSetUpLLVMStyleRTTI.html)?

Probably. I'd like to get rid of exceptions and dynamic RTTI from the compiler and that's a good and well documented way of doing so. But I'm biased by having worked with LLVM for too long, so I'm open to new ideas.

> * How are variants traversed, aka [the expression problem](https://en.wikipedia.org/wiki/Expression_problem):

We'll need to traverse the AST from both the parser and the MLIR generator, which may be completely different infrastructures. Making them similar could simplify the traversal algorithms, but we need to be careful on how much that'll make other infrastructure more complex.

> * How are source locations represented? Do all nodes carry a location, or only select ones?

Every node has location that was set by the PEG parser. Both AST and MLIR require source locations to be propagated.

New nodes are created "from" old ones, taking their source location.

```
Ast foo = ast::node(bar, "name");
assert(foo.path == bar.path && foo.line == bar.line && foo.column == bar.column);
```

Those locations are passed to MLIR via:

```
auto path = AST::getPath(ast);
return builder.getFileLineColLoc(Identifier::get(path.file, context), path.line, path.column);
```

We must maintain the same requirements to avoid losing the location half-way through.

>   * In particular, I think that after a dedicated resolution pass, all symbol references have direct pointers to the defining node. Ulterior passes can directly access that pointer and use it as a simple unique identifier, rather than reimplementing their own lookup tables.

I'm not sure what you mean here. Class types have a `get_def` function to retrieve their declared types, but I'm not sure variables can point to their declarations.

But in the MLIR we can't use the declarations in a nested symbol table, which will need to update the SSA values that correspond to the latest scoped value for each variable.


> * Can we reuse any of the original prototype's AST, visitor infrastructure and name resolution pass?

That'll depend if the AST we use ends up similar to that one, than most likely yes. But we'll have to introduce it slowly, so probably not all of it will be relevant initially.

**Comment by tobiasgrosser** [comment]
I am not yet very familiar with this project, but I wonder if it would be possible to represent the AST as an MLIR dialect? Or is there any technical reason that would make this difficult?

**Comment by mjp41** [comment]
@tobiasgrosser  we consider this a while ago, #101. @rengolin summarised our thinking at the time in: https://github.com/microsoft/verona/issues/101#issuecomment-629149425

**Comment by plietar** [comment]
> >  In particular, I think that after a dedicated resolution pass, all symbol references have direct pointers to the defining node. Ulterior passes can directly access that pointer and use it as a simple unique identifier, rather than reimplementing their own lookup tables.
>
> I'm not sure what you mean here. Class types have a get_def function to retrieve their declared types, but I'm not sure variables can point to their declarations.
>
> But in the MLIR we can't use the declarations in a nested symbol table, which will need to update the SSA values that correspond to the latest scoped value for each variable.

Take expressions for example, there will be a `LocalRef` node which references an existing variable declaration. When manipulating the AST (eg. when lowering to MLIR), we often need to find the corresponding declaration.

Currently in the generator we have a series of `String -> Value` maps to find the alloca from the variable's name, one per scope. Using names is pretty inefficient, full of footguns, and more complicated than it needs to be. In particular you need to implement all the non-trivial scoping rules. We already have a pass which implements the name resolution logic (`ref.cc`), but we're throwing all of that information away.

If the `LocalRef` had a pointer to the variable declaration, we could hash the pointer and have a single `LocalDecl* -> Value` map. There is no more problem shadowing or multiple declarations with the same name anymore, since the pointer's value is unique to each declaration. There is no need to worry about scoping rules and nested symbol tables. All this information is directly available to you.

In Clang's AST for example, [the `LocalRef` node holds a pointer to a `ValueDecl`](https://clang.llvm.org/doxygen/classclang_1_1DeclRefExpr.html#a22eec021070f5d0733e90b6c5c127a25).

**Comment by rengolin** [comment]
> If the `LocalRef` had a pointer to the variable declaration, we could hash the pointer and have a single `LocalDecl* -> Value` map. There is no more problem shadowing or multiple declarations with the same name anymore, since the pointer's value is unique to each declaration. There is no need to worry about scoping rules and nested symbol tables. All this information is directly available to you.

As discussed in other issues, this only works for things parsed or generated by the AST. Nodes, variables and functions generated on the MLIR side (lambdas, literals, behaviours) will all need to interact with this namespace and won't have AST nodes to point to.

Furthermore, scope is not only used to find the declaration of a variable, but also updates, which depend on the CFG and bring the correct SSA value in the local context. If we only look at the declaration we'll be ignoring any updates to variables and always using the original declared value.

Finally, updates on a local context will shadow the original declaration regardless if the map uses a string or a `LocalDecl*` to track updates.

**Comment by plietar** [comment]
> Nodes, variables and functions generated on the MLIR side (lambdas, literals, behaviours) will all need to interact with this namespace and won't have AST nodes to point to.

I don't know what "this namespace" is. An AST node cannot reference an MLIR concept, so there is no issue with making AST nodes have pointers to other AST nodes.

> If we only look at the declaration we'll be ignoring any updates to variables and always using the original declared value.

Of course. But we're only using the definition pointer as an identifier in the map. We can still update the map when we need to.

> Finally, updates on a local context will shadow the original declaration regardless if the map uses a string or a LocalDecl* to track updates.

Sorry I don't understand what this means.

**Comment by rengolin** [comment]
> I don't know what "this namespace" is.

Sorry, bad overloaded terminology.

MLIR values created from AST nodes will have a pointer to the declaration, auto-generated ones won't. If we want to have all of them sharing the same structures (maps and lists), then we'll need something that is common to both of them, which isn't AST nodes.

The language has two guarantees that strings work fine: first, there can be no variable shadowing, and second, there can be no overloading of function names in the whole class. Only one variable/function can exist in nested scopes with the same name.

I'm not saying it's efficient, I'm saying it's common and for now, works. Replacing strings with AST nodes will deprive us from the latter group, which "doesn't work". To optimise string maps we'll have to come up with something better.


> Of course. But we're only using the definition pointer as an identifier in the map. We can still update the map when we need to.

Exactly, so adding those pointers won't remove the need for scope maps in the generator, which is what I thought you meant.

Further to this point, the scope in MLIR is not necessarily the same as in the AST, because MLIR has control flow (block arguments) and different scope rules (dominating blocks, its own symbol table, etc). We can't assume we can just use the AST one, not we should force the AST one "look like" the MLIR one.

My current work in using block arguments instead of `alloca/load/store` has uncovered many of those cases which are not trivial.

> > Finally, updates on a local context will shadow the original declaration regardless if the map uses a string or a LocalDecl* to track updates.
> 
> Sorry I don't understand what this means.

That was terse, sorry. 

What I meant is that it doesn't matter what the map key is (node, string), we'll still need special scoping rules for MLIR that the AST doesn't know about, and therefore, will still have a scope map in the generator.

**Comment by plietar** [comment]
Honestly my main worry with strings is that we might end up having two implementations of name resolution in the compiler. These will unavoidably get out of sync in subtle ways. This is why I want a single pass responsible for it (which we already have), and store those results in the AST (or some side tables).

——

> MLIR values created from AST nodes will have a pointer to the declaration, auto-generated ones won't.

Do you have some more concrete example? Sorry I’m having a hard time understanding what your concern is. MLIR values will never point back to the AST. Really once the IR is built we should be able to throw the AST away.

**Comment by rengolin** [comment]
> Honestly my main worry with strings is that we might end up having two implementations of name resolution in the compiler. These will unavoidably get out of sync in subtle ways. This is why I want a single pass responsible for it (which we already have), and store those results in the AST (or some side tables).

Right now we're not doing name resolution at all in MLIR, we're relying on the parser to have verified it already. We just use the map to fetch the "up-to-date" SSA value of the symbol, which you'll still need regardless of what the key is.

> Do you have some more concrete example? Sorry I’m having a hard time understanding what your concern is. MLIR values will never point back to the AST. Really once the IR is built we should be able to throw the AST away.

Consider the following example:

```
// User class, from source, in the AST, has node pointer
class Foo {
  bar(a : U32, b : F64, c : bool) // from code
}

// Lambda class, compiler-generated, no AST nodes
class lambda$1 {
  // captured variables
  arg$1 : U32;
  arg$2 : F64;
  arg$3 : bool;
  // execution
  apply() { replaces "a" with "arg$1", etc. }
}
```

If I have a `map<Ast&, mlir::Value>`, I can only add `Foo::bar`, `Foo::bar::a`, etc. because the lambda created by the compiler doesn't have an `Ast` node and cannot be in that map. So I'd have to have another map, with strings or possibly more, to call that `apply()` function. 

It's still not clear (at least to me) how we'll link hygienic IDs with objects in the use/call site. It's possible strings won't be enough, in which case we'll have to think of something else, but an Ast node isn't it, because they will never have one.

De-sugaring is another source of compiler-generated variables and functions, but those were moved to the Ast, so (for now), they're not a problem anymore. We may still need to introduce some new concepts in the compiler that won't have a corresponding Ast node, and fixing the map's key to an Ast node will not help.

However, it's quite possible that you're right and we don't need anything other than Ast node pointers for the map's key, but this is not the time (nor issue #) to discuss this.

This discussion is orthogonal to a typed Ast. Even though a typed Ast reduces the need for external maps while handling *Ast constructs* it won't make a difference on the non-Ast ones.

**Comment by rengolin** [comment]
Just got here and realised we're now using a typed AST (see `src/parser`). So this issue can be closed.
