### ISSUE TITLE
Reachability analysis doesn't always visit receiver

### ISSUE THREAD

**Issue by lukecheeseman** [microsoft/verona#35]
Compiling the following:

```
class Cell[T] {
  foo(self: mut) {}
}

class B {
  bar(): Cell[U64Obj] & iso {
    new Cell
  }

  baz() {
    var a = B.bar();
    (mut-view a).foo();
  }
}

class Main {
  main() {
    B.baz();
  }
}
```
gives the error:
```
terminate called after throwing an instance of 'std::out_of_range'
  what():  map::at
```

It looks like the type Cell hasn't been visited in the Reachabilty pass as the following doesn't cause the same issue:

```
baz() {
  baz() {
    var c = new Cell;
    B.refine(mut-view c);
    var a = B.bar();
    (mut-view a).foo();
  }
}
```

**Comment by plietar** [comment]
This issue here is that the reachability pass has an invariant that the receiver type is always  visited before its methods. The rationale is that you can only call a method if you have a value, and you can only have a value if you've visited its type. It sort of worked so far, but apparently there's edge cases where it doesn't :(.

There's probably a way to fix that edge case, bu there's really no point keeping that assumption. @lukecheeseman has a simple fix coming soon.

**Comment by plietar** [comment]
Even smaller test case:
```
class A {
  foo(self: iso) {}
}

class B {
  bar(): A & iso {
    new A
  }
}

class Main {
  main() {
    (B.bar()).foo();
  }
}
```

I'm amazed we hadn't hit this bug before given how trivial it is to trigger it.
