### ISSUE TITLE
Rewriting the front-end?

### ISSUE THREAD

**Issue by rengolin** [microsoft/verona#351]
We're finding the limits in the peg library that are beginning to drag what we can do with the ast and we have an effort to create a new typed ast (#344), and we began to ask ourselves: is it worth writing a new front-end, from scratch?

There are two main questions that we need to answer to know which path to take:
1. How special could our grammar ever be?
2. How much infrastructure can we borrow from other projects?

The first question leads to decisions concerning using a peg parser (existing, new, hybrid) or something else. If if that, how special do we need it to be? 

It's hard to answer those questions at this time, so we may choose to only re-implement the actual parser and grammar if we find ourselves with no other choice.

The second question is about everything else in the parser. How do we traverse the language, organise files, keep metadata, source location, etc? How do we report errors, both in the parser itself, the MLIR generation, LLVM passes, etc?

If we chose to not use the current peg parser, can we reuse some infrastructure from Clang? If so, how much?

This is a long term issue that needs no quick solution. I'm just opening for us to start the discussion and keep in the back burner until we actually decide to act on it.

@plietar @sylvanc @davidchisnall @mjp41

**Comment by davidchisnall** [comment]
I'm not sure there's anything in Clang that we want to reuse.  The Clang parser is designed around tokens that can come from macro expansion (and so have to track multiple locations for each token) and is aggressively optimised because 1-10 MB compilation units are common for C-family languages.  Verona does not have macros and we probably won't do compile-time reflection / metaprogramming things in terms of token rewriting and our compilation units are likely to be <10 KB, so it's much less important to carefully optimise the parser.

In the old parser, we had something like Clang's `SourceLocation`, which embedded either a {file, line, column} tuple or an index into a table in a 32-bit integer.

**Comment by rengolin** [comment]
I didn't mean on the AST side, but some infrastructure that could make connecting to LLVM more amenable. Possibly just using the LLVM APIs would go a long way of reaching that goal, though.

**Comment by rengolin** [comment]
Ok, we seem to have converged to a custom parse with a typed AST into the old compiler for the first iteration of the IR, then MLIR and LLVM lowering later. We'll use whatever infrastructure from Clang/LLVM that is necessary, no need for a long discussion on it.
