### ISSUE TITLE
Few Notes/Suggestions

### ISSUE THREAD

**Issue by RUSshy** [microsoft/verona#36]
- Top level functions, new language, should we be forced again to create a class to have a main function?

- Generics syntax, ``class MyGeneric[T]``, doesn't that create unnecessary confusion/friction with the array syntax people are used to write in other languages?

**Comment by plietar** [comment]
> Top level functions, new language, should we be forced again to create a class to have a main function?

Note that the language is still at a very early stage. We've focused on a few key features, so some other design areas, such as the module system, are still lagging behind.

What I had in mind is that every module is actually a class with static methods only, the entry file is implicitly the `Main` module/class and has a static `main` method. So it will "feel" like main is a top-level function.

I just didn't want to bother implementing free functions if we're gonna have a nicer solution later.

> Generics syntax, class MyGeneric[T], doesn't that create unnecessary confusion/friction with the array syntax people are used to write in other languages?

The Java/C++/... angle bracket syntax is annoyingly ambiguous because it reuses the same symbol as comparison operator, so each language has had to come up with complicated solutions to work around it (eg. Rust's "turbofish" syntax, leaving spaces around in C++). Using square brackets side steps the issue.

There's some precedent in at least Pony and Scala for doing this.
