### ISSUE TITLE
please provided us prebuilt veronac, we want to learn verona language.

### ISSUE THREAD

**Issue by ghost** [microsoft/verona#388]
please provided us prebuilt veronac, we want to learn verona language.
I am watching verona project for a while, I noticed it nearly can be try for fun.

Please provide us the prebuilt veronac. may you please setup Github Actions, to produced  prebuilt veronac , and release them for alpha test?

that we can join the force, try and test the language. 

This can help us together contribute the project.

Next things, we can contribute language guide, document to help people getting start with the new language. 

How about your thought?

**Comment by rengolin** [comment]
Hi @netroby, thanks for your interest! We welcome your enthusiasm very much but it may be best to wait a bit more to start playing with the compiler.

The syntax is still currently in development and we still have three different front-ends at different levels of completeness. There are a number of factors in the development of these front-ends (and their back-ends) that will invariably affect syntax and semantics of the language. Hopefully we'll narrow down to a single front-end soon enough.

However, the idea of having Github actions to release alpha versions of the compiler (once it's in a better shape) is interesting. Once the compiler has matured a bit more and we're ready to ship some pre-built alpha version, we'll ping back on this issue.

Thank you!

**Comment by timmyjose** [comment]
It's September now, and we still don't have prebuilt binaries (even though the CI pipelines exist). This is a bit disappointing seeing as to how building from source takes a massive amount of time and space - the fully recursively cloned repo is almost 3.5GB, and the build process has been downloading from stuff - my local clone is already upwards of 4GB and growing even as I speak. Not all of us have high-end machines that can handle this level of heft. 

I know this is still early days, but providing binaries would help play around with the language, at least to see if one likes it, and may possibly use it/contribute to it/ignore it.

**Comment by davidchisnall** [comment]
Hi @timmyrose, thanks for your interest in the project.  If the download size is a problem then I suggest that you limit the recursive clone to depth 1, to avoid pulling in the complete history of LLVM (which is very large).  Note that you will need around 10-15GB of disk space for a release build and around 70GB for a debug build.

We are not yet providing binaries because the binaries that we build are not generally useful.  The language is incomplete and the compiler implements only a very small subset of the language (it does not yet, for example, support object allocation, I/O, or any of the concurrency features, so is basically limited to simple arithmetic) and there is no standard library implementation.  This is not sufficient to try out the language.

Verona is open sourced to facilitate collaboration with some universities that are working on the project with us as a research project.  We hope that it will be ready for some early experimentation in the new year.

**Comment by timmyjose** [comment]
@davidchisnall Thanks for the update! I did manage to use the prebuilt (CI) build of LLVM, and the total size of the clone is now around 7.1GB (which is still big, but manageable). The build process itself (once the prebuilt LLVM was downloaded) took very less time, so that was quite convenient. 

Yes, I see what you mean that the language is a work in progress. I noticed, for instance, that the test paths had changed a bit from what the docs mention (under `deprecated`). Still, it's a very interesting project that I'm keeping an eye out for - both for edification as well as possibly contributing to in the future. So , please keep up the good work!

Cheers.

**Comment by rengolin** [comment]
For reference, the `deprecated` programs were part of an internship implementing an older view of the language that is no longer true. We felt that people trying to use them would be confused when looking at the current implementation or reading our current documents in `docs/internal`.

If you want to understand how the new language syntax/semantics will look like, please check the internal documents.

**Comment by timmyjose** [comment]
@rengolin That's what I figured (sort of). The post-buld test instructions in`building.md` still point to the old path (`build\dist\veronac.exe --run testsuite\veronac\demo\run-pass\dining_phil.verona`). I think this path needs to be updated since there is no `veronac` directory under the testsuite directory anymore.

**Comment by rengolin** [comment]
Ah, my mistake. Though, those tests are not run anymore because they were unstable and would crash when run with sanitizers.
