### ISSUE TITLE
[CWE134] Using fmt::print to print string is very dangerous, leading to potential format string vulns.

### ISSUE THREAD

**Issue by swang206** [microsoft/verona#431]
https://github.com/microsoft/verona/blob/282e326640c9983c38cc72420102c34762c3c41d/src/interpreter/bytecode.cc#L15

Because it is the format string, not simply a string.

Technically they should be things like:

```cpp
fmt::print("{}","ADD");
```

See fast_io's main page.

https://github.com/expnkx/fast_io

See CWE https://cwe.mitre.org/data/definitions/134.html

**Comment by plietar** [comment]
I don’t think the CWE applies in this context.

In the file you linked to, all the format strings are constants. These are not externally controlled.

There is actually a place in the interpreter that calls fmtlib with an “externally controlled” string, namely the PRINT opcode. However the interpreter is not (for the time being) designed as a sandbox for executing untrusted bytecode. There are many ways a manually crafted bytecode can cause all sorts of memory corruption, in ways that are much worse than a format string vulnerability.

**Comment by davidchisnall** [comment]
I'm not sure why we're using `fmt` to print string literals, but there is nothing unsafe about this use.  The linked repository appears to be conflating a lot of different things.  

The C `printf` function and friends are unsafe because of the C variadic calling convention.  This means that an attacker who can control format strings can dereference arbitrary bits of the stack.  

The `fmt` library is type safe.  It does not use the C variadic calling convention, it uses variadic templates that construct typed tuples for the arguments and pass them to format string implementations that can access them by index and type without any mechanism for accessing arbitrary stack memory or variables with the incorrect type.

As the linked repo points out, an attacker-controlled format string can cause an exception.  This is a problem only if the exception is not checked and if the attacker can control the format string.

In the case linked to in our repo; however, the attacker is not in control of the format string.  The format string is a literal.  [The parameter to the function is the output stream to which the output will be sent](https://fmt.dev/latest/api.html#std-ostream-support).  As such, the linked examples are not examples of this CWE.

Please also note that this project is governed by the [Microsoft Open Source Code of Conduct](https://opensource.microsoft.com/codeofconduct/).  The attacks on other projects in the `fast_io` description are not welcome.  If you find examples of CWEs in our code, we would appreciate issues being raised linking to the code and the CWE, but there should be no need for personal attacks such as those on line 15 of the `fast_io` project's README, which directly insult the author of fmtlib.  This is not a respectful disagreement over technical issues, this is a direct personal attack against the author of a competing project.  Please do not post links to such material in our issue tracker.
