### ISSUE TITLE
Vim plugin for Verona

### ISSUE THREAD

**Issue by timmyjose** [microsoft/verona#504]
Hi all,

I have created a basic Vim plugin for Verona which also supports running the scripts (in interpreted mode) from within the buffer.  This *should* also work as-is on NeoVim, but I haven't tested that myself yet.

Here is the link to the repo:  https://github.com/timmyjose-projects/verona.vim

## Screenshots
(Light Mode):

![verona-vim-light-mode](https://user-images.githubusercontent.com/2051158/135276243-4fc8f29f-bd60-4c0c-97af-b74bc95f2462.png)
(Dark Mode):
![verona-vim-dark-mode](https://user-images.githubusercontent.com/2051158/135276034-6b668c58-57a8-418c-bf40-eb50120a31a8.png)

## Running programs 

(Using `<LocalLeader> r`)

![normal_mode_verona_run](https://user-images.githubusercontent.com/2051158/135276074-0030d746-afcb-4623-a441-9a6214068362.gif)

(Using the `Ex` mode command, `VeronaRun`):

![ex_mode_verona_run](https://user-images.githubusercontent.com/2051158/135276100-81fe50db-ad59-4176-a3cd-49566b507982.gif)

This is a basic version of the plugin. As the language grows, and my own understanding of the project grows, I plan to include more features as well as update the syntax highlighting.

Cheers!

**Comment by davidchisnall** [comment]
Great work, thanks!

Note that the interpreter is now deprecated, because it implements an old draft version of the language.  Syntax highlighting may not be possible with the built-in support in Vim, given all of the [user-defined control flow](https://github.com/microsoft/verona/blob/master/docs/internal/programmable-control-flow.md) work, but at some point we should have a stable enough parser that we can start thinking about exposing it over LSP.  I use [ALE](https://github.com/dense-analysis/ale) to talk to LSP implementations from Vim and I'd love to see it grow Verona support.

**Comment by rengolin** [comment]
User-defined control flow will indeed break a lot of static syntax highlighting and having that support would really make a difference. But for the time being, this is working fine on the examples in `testsuite`.

I'll reference this from the main page with the other editors. Thanks for the work!
