### ISSUE TITLE
handle_bind_or_connect - uninitialized stack buffer [defense-in-depth]

### ISSUE THREAD

**Issue by saaramar** [microsoft/verona#561]
The function `handle_bind_or_connect` does not initialized the `buffer` on the stack. In case the sandbox writes `length`==0, `buffer` will contain uninitialized stack from the parent.

It's NOT a security issue, because the length is passed on to netpolicy.invoke<Op>.  However, for defense-in-depth, we could consider memset0 it and set arguments one by one, with the appropriate types (similar to this commit https://github.com/microsoft/verona/commit/cd77fd469aeaa24714de26399840509b1b29122d).

@davidchisnall

**Comment by davidchisnall** [comment]
I don't think that we can set the arguments one by one, because `struct sockaddr` is a pretend type and the real argument is to some other type that depends on the address and protocol families.  We could zero the stack buffer, though any policy callee that does anything other than pass the buffer to the kernel should be doing length checks.  The kernel does a length check against the address and protocol families defined in the `socket` call.  This is hard for us to expose because the socket that we receive is not tightly coupled to the socket that we provided, so practically the only thing that you can usefully do with this buffer is see if it's a bit pattern that you returned from `getaddrinfo` as an address that the sandbox is allowed to pass to `connect` / `bind`.
