### ISSUE TITLE
Finaliser runs too early

### ISSUE THREAD

**Issue by lukecheeseman** [microsoft/verona#62]
The follow program:
```
use "list.verona"

class A {
  _id: U64 & imm;

  create(id: U64 & imm): A & iso {
    var result = new A;
    result._id = id;
    result
  }

  final(self: mut) {
    Builtin.print1("Finalising A: {:#}\n", self)
  }
}

class Cell {
  _pool: cown[Pool] & imm;
  _f: A & iso;

  create(pool: cown[Pool] & imm, f: A & iso): Cell & iso {
    var result = new Cell;
    result._pool = pool;
    result._f = f;
    result
  }

  final(self: mut) {
    Builtin.print1("Finalising Cell: {:#}\n", self);
    Pool.return(self._pool, self._f = A.create(1));
  }
}

class Pool {
  _f: A & iso;

  create(): cown[Pool] & imm {
    var result = new Pool;
    cown.create(result)
  }

  return(pool: cown[Pool] & imm, f: A & iso) {
    Builtin.print1("Returning A: {:#}\n", mut-view f);
    when (var p = pool) {
      // FIXME: at this point A stops existing
      Builtin.print1("A: {:#}\n", mut-view f);
      p._f = f;
    }
  }
}

class Main {
  main() {
    var pool = Pool.create();
    var c = Cell.create(pool, A.create(0));
  }
}
```
When run gives the following output:
```
Finalising Cell: Cell { cown[Pool](0x7fde1b010020), A { 0 } }
Returning A: A { 0 }
Finalising A: A { 0 }
fish: '../verona/build/dist/veronac ./…' terminated by signal SIGSEGV (Address boundary error)
```
The value passed to `return` is finalised before it's passed into the behaviour.

**Comment by lukecheeseman** [comment]
Talking with @plietar; the trace visits iso fields before running the finaliser runs, so the field is found to have no more references and gets GC'd too early.

**Comment by plietar** [comment]
When an object is collected, three things 
 need to happen:
1) run the user-defined finaliser
2) find all iso fields
3) delete VMObject’s `std::unique_ptr<FieldValue[]>`

2 must run before 3, and in order to support the “extract and send subregions” pattern in finalisers, 1 must run before 2.

However, currently from the runtime’s point of view, 1 and 3 are both part of VMObject’s finaliser and run together, before 2 does.

Possible solutions:
- expose a new hook in the runtime for step 3, distinguishing between an object’s finaliser and its destructor.
- let the finaliser trace the iso fields, allowing the VM to do all steps in the order it wants
- get rid of step 3, by storing the fields inline with the VMObject storage. This could be done with a C99 “flexible array member”, but it’s not very friendly to do in C++. In particular computing the size of the VMObject becomes tricky.

Before we had a VM, the runtime actually did trace the iso fields before running the finaliser, but I swapped those when introducing the fields array.

**Comment by plietar** [comment]
Note that when storing a string in a field, FieldValue’s destructor will also call std::string’s destructor. If we get rid of step 3 then we’d have to do this elsewhere (possibly in the finaliser).

**Comment by plietar** [comment]
@mjp41 has pointed out that we can’t destroy the fields array until all the finalisers in the region have run, as they could be traversing fields of other objects. Similarly we can’t be deallocating strings in the finaliser either (the strings should really be implemented as their own Verona object though).

If we want to keep the unique_ptr for the fields, what we really need is a second pass through the ring to run the destructors.
